<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Larysa Mendes de Almeida, Vitória Maria do Nascimento, Welly Remígio Bezerra">

<title>Regressão Linear Múltipla</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Relatorio_Carseats_files/libs/clipboard/clipboard.min.js"></script>
<script src="Relatorio_Carseats_files/libs/quarto-html/quarto.js"></script>
<script src="Relatorio_Carseats_files/libs/quarto-html/popper.min.js"></script>
<script src="Relatorio_Carseats_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Relatorio_Carseats_files/libs/quarto-html/anchor.min.js"></script>
<link href="Relatorio_Carseats_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Relatorio_Carseats_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Relatorio_Carseats_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Relatorio_Carseats_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Relatorio_Carseats_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><span class="header-section-number">1</span> Introdução</a></li>
  <li><a href="#os-dados" id="toc-os-dados" class="nav-link" data-scroll-target="#os-dados"><span class="header-section-number">2</span> Os dados</a>
  <ul class="collapse">
  <li><a href="#análise-exploratória-dos-dados" id="toc-análise-exploratória-dos-dados" class="nav-link" data-scroll-target="#análise-exploratória-dos-dados"><span class="header-section-number">2.1</span> Análise exploratória dos dados</a>
  <ul class="collapse">
  <li><a href="#comentários" id="toc-comentários" class="nav-link" data-scroll-target="#comentários"><span class="header-section-number">2.1.1</span> Comentários:</a></li>
  <li><a href="#sec-GGally" id="toc-sec-GGally" class="nav-link" data-scroll-target="#sec-GGally"><span class="header-section-number">2.1.2</span> Análise de Correlação</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#modelo-1-com-todas-as-variáveis" id="toc-modelo-1-com-todas-as-variáveis" class="nav-link" data-scroll-target="#modelo-1-com-todas-as-variáveis"><span class="header-section-number">3</span> Modelo 1 (Com todas as variáveis)</a>
  <ul class="collapse">
  <li><a href="#sec-modelo2selecionado" id="toc-sec-modelo2selecionado" class="nav-link" data-scroll-target="#sec-modelo2selecionado"><span class="header-section-number">3.1</span> Modelo sem <code>Population</code> (modelo2)</a></li>
  <li><a href="#modelo-sem-education-modelo3" id="toc-modelo-sem-education-modelo3" class="nav-link" data-scroll-target="#modelo-sem-education-modelo3"><span class="header-section-number">3.2</span> Modelo sem <code>Education</code> (modelo3)</a></li>
  <li><a href="#modelo-sem-urban-modelo4" id="toc-modelo-sem-urban-modelo4" class="nav-link" data-scroll-target="#modelo-sem-urban-modelo4"><span class="header-section-number">3.3</span> Modelo sem <code>Urban</code> (modelo4)</a></li>
  <li><a href="#modelo-sem-us-modelo5" id="toc-modelo-sem-us-modelo5" class="nav-link" data-scroll-target="#modelo-sem-us-modelo5"><span class="header-section-number">3.4</span> Modelo sem <code>US</code> (modelo5)</a></li>
  <li><a href="#modelo-sem-population-education-urban-e-us-modelo6" id="toc-modelo-sem-population-education-urban-e-us-modelo6" class="nav-link" data-scroll-target="#modelo-sem-population-education-urban-e-us-modelo6"><span class="header-section-number">3.5</span> Modelo sem <code>Population</code>, <code>Education</code>, <code>Urban</code> e <code>US</code> (modelo6)</a></li>
  </ul></li>
  <li><a href="#métodos-de-seleção-de-modelos" id="toc-métodos-de-seleção-de-modelos" class="nav-link" data-scroll-target="#métodos-de-seleção-de-modelos"><span class="header-section-number">4</span> Métodos de seleção de modelos</a>
  <ul class="collapse">
  <li><a href="#medida-aic" id="toc-medida-aic" class="nav-link" data-scroll-target="#medida-aic"><span class="header-section-number">4.1</span> Medida AIC</a></li>
  <li><a href="#comparação-de-modelos-encaixados-anova" id="toc-comparação-de-modelos-encaixados-anova" class="nav-link" data-scroll-target="#comparação-de-modelos-encaixados-anova"><span class="header-section-number">4.2</span> Comparação de modelos encaixados (ANOVA)</a></li>
  </ul></li>
  <li><a href="#modelo-selecionado-modelo6" id="toc-modelo-selecionado-modelo6" class="nav-link" data-scroll-target="#modelo-selecionado-modelo6"><span class="header-section-number">5</span> Modelo selecionado (modelo6)</a>
  <ul class="collapse">
  <li><a href="#análises-dos-pressupostos-e-comentários" id="toc-análises-dos-pressupostos-e-comentários" class="nav-link" data-scroll-target="#análises-dos-pressupostos-e-comentários"><span class="header-section-number">5.1</span> Análises dos pressupostos e Comentários</a></li>
  </ul></li>
  <li><a href="#interpretações-do-modelo-selecionado" id="toc-interpretações-do-modelo-selecionado" class="nav-link" data-scroll-target="#interpretações-do-modelo-selecionado"><span class="header-section-number">6</span> Interpretações do modelo selecionado</a>
  <ul class="collapse">
  <li><a href="#relato-em-português" id="toc-relato-em-português" class="nav-link" data-scroll-target="#relato-em-português"><span class="header-section-number">6.0.1</span> Relato em português:</a></li>
  <li><a href="#coeficientes-padronizados" id="toc-coeficientes-padronizados" class="nav-link" data-scroll-target="#coeficientes-padronizados"><span class="header-section-number">6.1</span> Coeficientes padronizados</a></li>
  </ul></li>
  <li><a href="#previsões" id="toc-previsões" class="nav-link" data-scroll-target="#previsões"><span class="header-section-number">7</span> Previsões</a>
  <ul class="collapse">
  <li><a href="#intervalo-de-confiança" id="toc-intervalo-de-confiança" class="nav-link" data-scroll-target="#intervalo-de-confiança"><span class="header-section-number">7.1</span> Intervalo de Confiança</a></li>
  <li><a href="#intervalo-de-prediçãoprevisão" id="toc-intervalo-de-prediçãoprevisão" class="nav-link" data-scroll-target="#intervalo-de-prediçãoprevisão"><span class="header-section-number">7.2</span> Intervalo de Predição/Previsão</a></li>
  </ul></li>
  <li><a href="#conclusão" id="toc-conclusão" class="nav-link" data-scroll-target="#conclusão"><span class="header-section-number">8</span> Conclusão</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regressão Linear Múltipla</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Larysa Mendes de Almeida, Vitória Maria do Nascimento, Welly Remígio Bezerra </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">7 de outubro de 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Setup para o relatório Quarto</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">message =</span> <span class="cn">FALSE</span>, <span class="at">warning =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Definindo o espelho do CRAN</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">repos =</span> <span class="fu">c</span>(<span class="at">CRAN =</span> <span class="st">"https://cloud.r-project.org/"</span>))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introdução" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introdução</h1>
<p>Este relatório tem por objetivo ajustar um modelo de regressão linear múltiplo com o intuito de investigar a influência de determinadas características associadas a vendas de cadeirinhas de carro para crianças e diversos fatores que podem influenciar essas vendas.</p>
<p>Neste contexto a regressão será realizada sobre base de dados <code>Carseats</code>, que trata das vendas de cadeirinhas de carro para crianças (Child Car Seats) em diferentes locais. Essa base está na biblioteca ISLR (An Introduction to Statistical Learning with Applications in R) que é um pacote em R que acompanha o famoso livro “An Introduction to Statistical Learning” (ISLR). Ela contém vários conjuntos de dados usados para demonstrar técnicas de aprendizado estatístico e machine learning. Esta base de dados contém onze variáveis, sendo três qualitativas e as demais quantitativas.</p>
</section>
<section id="os-dados" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Os dados</h1>
<p>É possível baixar os dados do livro <a href="https://www.statlearning.com/">An Introduction to Statistical Learning with applications in R</a>, mas o pacote <code>ISLR</code> pode ser baixado diretamente do <em>R</em>, para acessar a base de dados, <code>Carseats</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ISLR"</span>, <span class="at">quiet=</span><span class="cn">TRUE</span>) <span class="co">#instalando pacote</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>package 'ISLR' successfully unpacked and MD5 sums checked</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR) <span class="co">#chamando pacote</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">write.table</span>(Carseats , <span class="at">file=</span><span class="st">"dados_carseats.csv"</span>, <span class="at">sep=</span><span class="st">";"</span>, <span class="at">dec=</span><span class="st">","</span>) <span class="co">#criando arquivo .csv no local de </span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Descrição da Base de Dados: Número de observações: 400 Variável Resposta: - <code>Sales</code>: Vendas de cadeirinhas de carro em diferentes locais. (Milhares de unidades)</p>
<p>Variáveis Explicativas: - <code>CompPrice</code>: Preço da cadeirinha na loja concorrente. (em dólares).<br>
- <code>Income</code>: Renda média dos consumidores naquela região. (em milhares de dólares).<br>
- <code>Advertising</code>: Valor gasto em publicidade para aquela região (em milhares de dólares).<br>
- <code>Population</code>: População da região. (em milhares).<br>
- <code>Price</code>: Preço da cadeirinha de carro na loja.(em dólares).<br>
- <code>ShelveLoc</code>: Qualidade da localização da prateleira na loja. (“Good”, “Medium”, “Bad”).<br>
- <code>Age</code>: Idade média da população na região. (em anos).<br>
- <code>Education</code>: Nível médio de educação da população na região.(em anos).<br>
- <code>Urban</code>: Um fator que indica se a região é urbana. (“Yes” ou “No”).<br>
- <code>US</code>: Um fator que indica se a loja está nos EUA. (“Yes” ou “No”).</p>
<section id="análise-exploratória-dos-dados" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="análise-exploratória-dos-dados"><span class="header-section-number">2.1</span> Análise exploratória dos dados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> Carseats</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(dados)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">dados</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">400</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">ordered</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: left;">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ShelveLoc</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Med: 219, Bad: 96, Goo: 85</td>
</tr>
<tr class="even">
<td style="text-align: left;">Urban</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Yes: 282, No: 118</td>
</tr>
<tr class="odd">
<td style="text-align: left;">US</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Yes: 258, No: 142</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 3%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sales</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7.50</td>
<td style="text-align: right;">2.82</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5.39</td>
<td style="text-align: right;">7.49</td>
<td style="text-align: right;">9.32</td>
<td style="text-align: right;">16.27</td>
<td style="text-align: left;">▁▆▇▃▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">CompPrice</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">124.97</td>
<td style="text-align: right;">15.33</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">115.00</td>
<td style="text-align: right;">125.00</td>
<td style="text-align: right;">135.00</td>
<td style="text-align: right;">175.00</td>
<td style="text-align: left;">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Income</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">68.66</td>
<td style="text-align: right;">27.99</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">42.75</td>
<td style="text-align: right;">69.00</td>
<td style="text-align: right;">91.00</td>
<td style="text-align: right;">120.00</td>
<td style="text-align: left;">▇▆▇▆▅</td>
</tr>
<tr class="even">
<td style="text-align: left;">Advertising</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6.64</td>
<td style="text-align: right;">6.65</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">29.00</td>
<td style="text-align: left;">▇▃▃▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Population</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">264.84</td>
<td style="text-align: right;">147.38</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">139.00</td>
<td style="text-align: right;">272.00</td>
<td style="text-align: right;">398.50</td>
<td style="text-align: right;">509.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">Price</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">115.80</td>
<td style="text-align: right;">23.68</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">117.00</td>
<td style="text-align: right;">131.00</td>
<td style="text-align: right;">191.00</td>
<td style="text-align: left;">▁▂▇▆▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">53.32</td>
<td style="text-align: right;">16.20</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">39.75</td>
<td style="text-align: right;">54.50</td>
<td style="text-align: right;">66.00</td>
<td style="text-align: right;">80.00</td>
<td style="text-align: left;">▇▆▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">Education</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">13.90</td>
<td style="text-align: right;">2.62</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">14.00</td>
<td style="text-align: right;">16.00</td>
<td style="text-align: right;">18.00</td>
<td style="text-align: left;">▇▇▃▇▇</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="comentários" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="comentários"><span class="header-section-number">2.1.1</span> Comentários:</h3>
<p>De acordo com a tabela é possível observar que não há ausência de dados. O conjunto contém tanto as variáveis numéricas (como <code>Sales</code>, <code>CompPrice</code>, <code>Income</code>, <code>Advertising</code>, <code>Population</code>, <code>Price</code>, <code>Age</code>) quanto as categóricas (como <code>ShelveLoc</code>, <code>Urban</code> e <code>US</code>). As variáveis numéricas foram descritas por meio de estatísticas como média, mediana, desvio padrão e percentis, fornecendo uma visão clara sobre sua distribuição.</p>
</section>
<section id="sec-GGally" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="sec-GGally"><span class="header-section-number">2.1.2</span> Análise de Correlação</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"GGally"</span>, <span class="at">quite=</span><span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>package 'GGally' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
    C:\Users\Notebook\AppData\Local\Temp\Rtmp2h3han\downloaded_packages</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)<span class="co"># Pacote para função ggpairs</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="do">### Multicolinearidade: r &gt; 0.9 (ou 0.8)</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico com a variável qualitativa US</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>graf1 <span class="ot">&lt;-</span> <span class="fu">ggpairs</span>(dados, </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">columns =</span> <span class="fu">c</span>(<span class="st">"Sales"</span>, <span class="st">"CompPrice"</span>, <span class="st">"Income"</span>, <span class="st">"Advertising"</span>, <span class="st">"Population"</span>, <span class="st">"Price"</span>, <span class="st">"Age"</span>, <span class="st">"Education"</span>), </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>                 ggplot2<span class="sc">::</span><span class="fu">aes</span>(<span class="at">colour=</span>US), </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">upper =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"cor"</span>, <span class="at">size =</span> <span class="dv">3</span>)), </span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>                 <span class="at">lower =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="st">"points"</span>)) <span class="sc">+</span>            </span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span>                                              </span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>),                      </span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"bottom"</span>,                              </span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>))    </span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>graf1</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_Carseats_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico com a variável qualitativa Urban</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>graf2 <span class="ot">&lt;-</span> <span class="fu">ggpairs</span>(dados, </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">columns =</span> <span class="fu">c</span>(<span class="st">"Sales"</span>, <span class="st">"CompPrice"</span>, <span class="st">"Income"</span>, <span class="st">"Advertising"</span>, <span class="st">"Population"</span>, <span class="st">"Price"</span>, <span class="st">"Age"</span>, <span class="st">"Education"</span>), </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                 ggplot2<span class="sc">::</span><span class="fu">aes</span>(<span class="at">colour=</span>Urban), </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">upper =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"cor"</span>, <span class="at">size =</span> <span class="dv">3</span>)), </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">lower =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="st">"points"</span>)) <span class="sc">+</span>            </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span>                                              </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>),                      </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"bottom"</span>,                              </span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>))    </span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>graf2</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_Carseats_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico com a variável qualitativa ShelveLoc</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>graf3 <span class="ot">&lt;-</span> <span class="fu">ggpairs</span>(dados, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">columns =</span> <span class="fu">c</span>(<span class="st">"Sales"</span>, <span class="st">"CompPrice"</span>, <span class="st">"Income"</span>, <span class="st">"Advertising"</span>, <span class="st">"Population"</span>, <span class="st">"Price"</span>, <span class="st">"Age"</span>, <span class="st">"Education"</span>), </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>                 ggplot2<span class="sc">::</span><span class="fu">aes</span>(<span class="at">colour=</span>ShelveLoc), </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">upper =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"cor"</span>, <span class="at">size =</span> <span class="dv">3</span>)), </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">lower =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="st">"points"</span>)) <span class="sc">+</span>            </span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span>                                              </span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>),                      </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"bottom"</span>,                              </span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>))    </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>graf3</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_Carseats_files/figure-html/unnamed-chunk-3-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Salvando o gráfico em .jpeg</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"Grafico_dispersao_carseats.jpeg"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="comentários-1" class="level4" data-number="2.1.2.1">
<h4 data-number="2.1.2.1" class="anchored" data-anchor-id="comentários-1"><span class="header-section-number">2.1.2.1</span> Comentários</h4>
<p>Com relação à análise de correlação é algo desejável observar altas correlações das variáveis independentes com relação à variável dependente que no presente caso é <code>Sales</code>.</p>
<p>Por outro lado, altas correlações entre as demais variáveis a serem utilizadas como variáveis independentes nos dá indícios de que haverá <strong>problemas de multicolinearidade</strong> ao ajustar o MRLM. <strong>Como regra geral</strong> isto ocorre quando há <strong>correlações</strong> <span class="math inline">\(\geq 0.9\)</span> ou <span class="math inline">\(\geq 0.8\)</span> <strong>entre</strong> as <strong>variáveis preditoras</strong>.</p>
<p>Dito isto, é possível observar que:</p>
<ol type="1">
<li><p>A variável dependente <code>Sales</code>:</p>
<ol type="i">
<li><p>não apresenta correlação linear significante com a variável <code>CompPrice</code> (r= 0,064, p &gt; 0.10);</p></li>
<li><p>apresenta correlação linear significante com a variável <code>Income</code> (r= 0.152, p &lt; 0.001);</p></li>
<li><p>apresenta correlação linear significante com a variável <code>Advertising</code> (r= 0.270, p &lt; 0.001);</p></li>
<li><p>não apresenta correlação linear significante com a variável <code>Population</code> (r= 0.050, p &gt; 0.10);</p></li>
<li><p>apresenta correlação linear significante com a variável <code>Price</code> (r= -0.445, p &lt; 0.001);</p></li>
<li><p>apresenta correlação linear significante com a variável <code>Age</code> (r= -0.232, p &lt; 0.001);</p></li>
<li><p>não apresenta correlação linear significante com a variável <code>Education</code> (r= -0.052, p &gt; 0.10);</p></li>
</ol></li>
</ol>
</section>
<section id="multicolinearidade---analisando-o-vif---variance-inflation-factor" class="level4" data-number="2.1.2.2">
<h4 data-number="2.1.2.2" class="anchored" data-anchor-id="multicolinearidade---analisando-o-vif---variance-inflation-factor"><span class="header-section-number">2.1.2.2</span> Multicolinearidade - Analisando o VIF - Variance Inflation Factor</h4>
<p>Uma maneira de identificar a multicolinearidade é através do <strong>Fator de Inflação da Variância (VIF)</strong>.</p>
<p>O <strong>VIF é calculado</strong> para cada preditor fazendo uma regressão linear desse preditor em todos os outros preditores e, então, obtendo o <span class="math inline">\(R^2\)</span> dessa regressão. O VIF é apenas <span class="math inline">\(1/(1-R^2)\)</span>.</p>
<p><strong>Como interpretar o VIF?</strong><br>
</p>
<blockquote class="blockquote">
<p>Um <strong>valor maior que 5</strong> indica correlação <strong>potencialmente grave</strong> entre uma determinada variável preditora e outras variáveis preditoras no modelo. Nesse caso, as estimativas de coeficiente e os valores de p na saída da regressão provavelmente não são confiáveis.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>VIF &gt; 10</strong> indica <strong>problema de multicolinearidade</strong>.</p>
</blockquote>
<p>Veja abaixo <strong>como obter o vif</strong> usando o <em>R</em>, desconsiderando as variáveis ShelveLoc, US e Urban.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajuste do modelo de regressão linear múltiplo</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>modelo1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sales <span class="sc">~</span> CompPrice <span class="sc">+</span> Income <span class="sc">+</span> Advertising <span class="sc">+</span> Population <span class="sc">+</span> Price <span class="sc">+</span> ShelveLoc <span class="sc">+</span> Age <span class="sc">+</span> Education <span class="sc">+</span> Urban <span class="sc">+</span> US, <span class="at">data =</span> dados)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Uma opção para obter o: Variance Inflation Factor (VIF)</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car) </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(modelo1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                GVIF Df GVIF^(1/(2*Df))
CompPrice   1.554618  1        1.246843
Income      1.024731  1        1.012290
Advertising 2.103136  1        1.450219
Population  1.145534  1        1.070296
Price       1.537068  1        1.239785
ShelveLoc   1.033891  2        1.008367
Age         1.021051  1        1.010471
Education   1.026342  1        1.013086
Urban       1.022705  1        1.011289
US          1.980720  1        1.407380</code></pre>
</div>
</div>
<p>Como podemos ver, nenhuma das variáveis tem o VIF &gt; 10, logo, não há multicolinearidade.</p>
</section>
</section>
</section>
</section>
<section id="modelo-1-com-todas-as-variáveis" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Modelo 1 (Com todas as variáveis)</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ CompPrice + Income + Advertising + Population + 
    Price + ShelveLoc + Age + Education + Urban + US, data = dados)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.8692 -0.6908  0.0211  0.6636  3.4115 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      5.6606231  0.6034487   9.380  &lt; 2e-16 ***
CompPrice        0.0928153  0.0041477  22.378  &lt; 2e-16 ***
Income           0.0158028  0.0018451   8.565 2.58e-16 ***
Advertising      0.1230951  0.0111237  11.066  &lt; 2e-16 ***
Population       0.0002079  0.0003705   0.561    0.575    
Price           -0.0953579  0.0026711 -35.700  &lt; 2e-16 ***
ShelveLocGood    4.8501827  0.1531100  31.678  &lt; 2e-16 ***
ShelveLocMedium  1.9567148  0.1261056  15.516  &lt; 2e-16 ***
Age             -0.0460452  0.0031817 -14.472  &lt; 2e-16 ***
Education       -0.0211018  0.0197205  -1.070    0.285    
UrbanYes         0.1228864  0.1129761   1.088    0.277    
USYes           -0.1840928  0.1498423  -1.229    0.220    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.019 on 388 degrees of freedom
Multiple R-squared:  0.8734,    Adjusted R-squared:  0.8698 
F-statistic: 243.4 on 11 and 388 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Ao observar o primeiro modelo com o intuito de prever a variável <code>Sales</code>, tem-se que aproximadamente 87,34% (Multiple R-squared: 0,8734) da variação nas vendas é explicada pelas variáveis independentes, o que é um bom ajuste. Um valor de 86,98% (Adjusted R-squared: 0,8698) confirma que, mesmo ajustando para o número de variáveis no modelo, o ajuste ainda é forte. Isso é importante porque evita o viés de um R² inflado quando são adicionados mais preditores.</p>
<p>O valor de F elevado e o p-valor muito baixo (&lt; 2.2e-16) indicam que o modelo, como um todo, é estatisticamente significativo, ou seja, pelo menos uma das variáveis independentes está associada às vendas.</p>
<p>O modelo de regressão parece fornecer uma boa explicação para as vendas com base nas variáveis incluídas, especialmente o preço (<code>Price</code>), o preço dos concorrentes (<code>CompPrice</code>), a renda (<code>Income</code>), a publicidade (<code>Advertising</code>) e a idade (<code>Age</code>). Contudo, <code>Population</code>, <code>Education</code>, <code>Urban</code> e <code>US</code> não se mostraram significativas.</p>
<section id="sec-modelo2selecionado" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-modelo2selecionado"><span class="header-section-number">3.1</span> Modelo sem <code>Population</code> (modelo2)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>modelo2 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1, <span class="sc">~</span> . <span class="sc">-</span> Population)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo2)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ CompPrice + Income + Advertising + Price + 
    ShelveLoc + Age + Education + Urban + US, data = dados)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.8799 -0.7015  0.0088  0.6611  3.4268 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      5.761899   0.575319  10.015  &lt; 2e-16 ***
CompPrice        0.092609   0.004128  22.436  &lt; 2e-16 ***
Income           0.015774   0.001843   8.560 2.65e-16 ***
Advertising      0.125044   0.010558  11.844  &lt; 2e-16 ***
Price           -0.095302   0.002667 -35.736  &lt; 2e-16 ***
ShelveLocGood    4.846736   0.152852  31.709  &lt; 2e-16 ***
ShelveLocMedium  1.952145   0.125732  15.526  &lt; 2e-16 ***
Age             -0.046119   0.003176 -14.520  &lt; 2e-16 ***
Education       -0.022411   0.019565  -1.145    0.253    
UrbanYes         0.118853   0.112648   1.055    0.292    
USYes           -0.199075   0.147315  -1.351    0.177    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.018 on 389 degrees of freedom
Multiple R-squared:  0.8733,    Adjusted R-squared:  0.8701 
F-statistic: 268.2 on 10 and 389 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Observa-se que para este modelo ajustado ocorreu um aumento no valor da adequação de ajuste do modelo para 87,01% (Adjusted R-squared: 0.8701). Esse aumento indica que o modelo, sem a variável <code>Population</code>, consegue explicar uma maior proporção da variação total das vendas, tornando-o mais eficiente.</p>
</blockquote>
</section>
<section id="modelo-sem-education-modelo3" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="modelo-sem-education-modelo3"><span class="header-section-number">3.2</span> Modelo sem <code>Education</code> (modelo3)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>modelo3 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1, <span class="sc">~</span> . <span class="sc">-</span> Education)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo3)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ CompPrice + Income + Advertising + Population + 
    Price + ShelveLoc + Age + Urban + US, data = dados)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.7878 -0.7092  0.0175  0.6789  3.3754 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      5.3468659  0.5275196  10.136   &lt;2e-16 ***
CompPrice        0.0927626  0.0041481  22.362   &lt;2e-16 ***
Income           0.0159032  0.0018431   8.629   &lt;2e-16 ***
Advertising      0.1223177  0.0111020  11.018   &lt;2e-16 ***
Population       0.0002548  0.0003679   0.692    0.489    
Price           -0.0953725  0.0026715 -35.699   &lt;2e-16 ***
ShelveLocGood    4.8557953  0.1530486  31.727   &lt;2e-16 ***
ShelveLocMedium  1.9597110  0.1260980  15.541   &lt;2e-16 ***
Age             -0.0460665  0.0031822 -14.476   &lt;2e-16 ***
UrbanYes         0.1276924  0.1129078   1.131    0.259    
USYes           -0.1693875  0.1492386  -1.135    0.257    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.019 on 389 degrees of freedom
Multiple R-squared:  0.873, Adjusted R-squared:  0.8698 
F-statistic: 267.5 on 10 and 389 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Observa-se que para este modelo ajustado o valor da adequação de ajuste do modelo continuou igual ao modelo 1 com 86,98% (Adjusted R-squared: 0.8698). Isso indica que a variável <code>Education</code> não estava contribuindo significativamente para a explicação das vendas e, portanto, sua remoção não afetou o desempenho do modelo.</p>
</blockquote>
</section>
<section id="modelo-sem-urban-modelo4" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="modelo-sem-urban-modelo4"><span class="header-section-number">3.3</span> Modelo sem <code>Urban</code> (modelo4)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>modelo4 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1, <span class="sc">~</span> . <span class="sc">-</span> Urban)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo4)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ CompPrice + Income + Advertising + Population + 
    Price + ShelveLoc + Age + Education + US, data = dados)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.8498 -0.6992  0.0300  0.6436  3.4616 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      5.7267269  0.6005220   9.536   &lt;2e-16 ***
CompPrice        0.0930440  0.0041433  22.457   &lt;2e-16 ***
Income           0.0158656  0.0018447   8.601   &lt;2e-16 ***
Advertising      0.1235923  0.0111169  11.118   &lt;2e-16 ***
Population       0.0001822  0.0003698   0.493    0.622    
Price           -0.0953182  0.0026715 -35.680   &lt;2e-16 ***
ShelveLocGood    4.8365318  0.1526307  31.688   &lt;2e-16 ***
ShelveLocMedium  1.9458754  0.1257409  15.475   &lt;2e-16 ***
Age             -0.0459156  0.0031802 -14.438   &lt;2e-16 ***
Education       -0.0219546  0.0197095  -1.114    0.266    
USYes           -0.1836133  0.1498769  -1.225    0.221    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.019 on 389 degrees of freedom
Multiple R-squared:  0.873, Adjusted R-squared:  0.8698 
F-statistic: 267.5 on 10 and 389 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Observa-se que para este modelo ajustado o valor da adequação de ajuste do modelo continuou igual ao modelo 1 com 86,98% (Adjusted R-squared: 0.8698). Isso indica que a variável <code>Urban</code> não estava contribuindo significativamente para a explicação das vendas e, portanto, sua remoção não afetou o desempenho do modelo.</p>
</blockquote>
</section>
<section id="modelo-sem-us-modelo5" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="modelo-sem-us-modelo5"><span class="header-section-number">3.4</span> Modelo sem <code>US</code> (modelo5)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>modelo5 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1, <span class="sc">~</span> . <span class="sc">-</span> US)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo5)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ CompPrice + Income + Advertising + Population + 
    Price + ShelveLoc + Age + Education + Urban, data = dados)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.8596 -0.7088  0.0363  0.6693  3.2979 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      5.5811103  0.6003608   9.296  &lt; 2e-16 ***
CompPrice        0.0927157  0.0041496  22.343  &lt; 2e-16 ***
Income           0.0156692  0.0018431   8.501 4.06e-16 ***
Advertising      0.1136245  0.0080249  14.159  &lt; 2e-16 ***
Population       0.0002890  0.0003648   0.792    0.429    
Price           -0.0954252  0.0026723 -35.710  &lt; 2e-16 ***
ShelveLocGood    4.8486758  0.1532053  31.648  &lt; 2e-16 ***
ShelveLocMedium  1.9661745  0.1259527  15.610  &lt; 2e-16 ***
Age             -0.0461184  0.0031832 -14.488  &lt; 2e-16 ***
Education       -0.0188798  0.0196502  -0.961    0.337    
UrbanYes         0.1224780  0.1130495   1.083    0.279    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.02 on 389 degrees of freedom
Multiple R-squared:  0.8729,    Adjusted R-squared:  0.8697 
F-statistic: 267.2 on 10 and 389 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Observa-se que para este modelo ajustado o valor da adequação de ajuste do modelo diminuiu em comparação com o modelo 1, ficando com 86,97% (Adjusted R-squared: 0.8697). Isso indica que a variável <code>US</code> tem uma influência pequena, mas presente, na explicação das vendas.</p>
</blockquote>
</section>
<section id="modelo-sem-population-education-urban-e-us-modelo6" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="modelo-sem-population-education-urban-e-us-modelo6"><span class="header-section-number">3.5</span> Modelo sem <code>Population</code>, <code>Education</code>, <code>Urban</code> e <code>US</code> (modelo6)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>modelo6 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo1, <span class="sc">~</span> . <span class="sc">-</span>Population <span class="sc">-</span> Education <span class="sc">-</span> Urban <span class="sc">-</span> US)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo6)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ CompPrice + Income + Advertising + Price + 
    ShelveLoc + Age, data = dados)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.7728 -0.6954  0.0282  0.6732  3.3292 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      5.475226   0.505005   10.84   &lt;2e-16 ***
CompPrice        0.092571   0.004123   22.45   &lt;2e-16 ***
Income           0.015785   0.001838    8.59   &lt;2e-16 ***
Advertising      0.115903   0.007724   15.01   &lt;2e-16 ***
Price           -0.095319   0.002670  -35.70   &lt;2e-16 ***
ShelveLocGood    4.835675   0.152499   31.71   &lt;2e-16 ***
ShelveLocMedium  1.951993   0.125375   15.57   &lt;2e-16 ***
Age             -0.046128   0.003177  -14.52   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.019 on 392 degrees of freedom
Multiple R-squared:  0.872, Adjusted R-squared:  0.8697 
F-statistic: 381.4 on 7 and 392 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Observa-se que para este modelo ajustado o valor da adequação de ajuste do modelo diminuiu em comparação com o modelo 1, ficando com 86,97% (Adjusted R-squared: 0.8697).A exclusão das variáveis <code>Population</code>, <code>Education</code>, <code>Urban</code> e <code>US</code> resultou em um modelo mais simples, com uma redução mínima na capacidade de explicar as vendas.</p>
</blockquote>
</section>
</section>
<section id="métodos-de-seleção-de-modelos" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Métodos de seleção de modelos</h1>
<section id="medida-aic" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="medida-aic"><span class="header-section-number">4.1</span> Medida AIC</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1163.974</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo2)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1162.299</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo3)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1163.153</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo4)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1163.192</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo5)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1163.527</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo6)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1160.47</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Comparando-se os seis modelos verificou-se que o modelo com menor valor AIC é o modelo 6 e, portanto, o preferível.</p>
</blockquote>
</section>
<section id="comparação-de-modelos-encaixados-anova" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="comparação-de-modelos-encaixados-anova"><span class="header-section-number">4.2</span> Comparação de modelos encaixados (ANOVA)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo6, modelo1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Sales ~ CompPrice + Income + Advertising + Price + ShelveLoc + 
    Age
Model 2: Sales ~ CompPrice + Income + Advertising + Population + Price + 
    ShelveLoc + Age + Education + Urban + US
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1    392 407.39                           
2    388 402.83  4    4.5533 1.0964  0.358</code></pre>
</div>
</div>
<p>O teste ANOVA indica que a diferença entre os dois modelos não é estatisticamente significativa (p = 0.358), sugerindo que o modelo mais simples (modelo6), sem essas variáveis adicionais, é preferível por ser mais mais simples e possuir a mesma capacidade de ajuste. Assim, o modelo 6 é o mais adequado, pois não há ganho significativo ao adicionar as variáveis extras, e isso ajuda a evitar a complexidade desnecessária.</p>
</section>
</section>
<section id="modelo-selecionado-modelo6" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Modelo selecionado (modelo6)</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo6)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_Carseats_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_Carseats_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_Carseats_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_Carseats_files/figure-html/unnamed-chunk-13-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="análises-dos-pressupostos-e-comentários" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="análises-dos-pressupostos-e-comentários"><span class="header-section-number">5.1</span> Análises dos pressupostos e Comentários</h2>
<p>Pode-se observar no primeiro gráfico <em>Residuals vs Fitted</em> que o modelo apresenta uma boa linearidade, já que a linha vermelha indica uma relação linear quando está próxima da linha cinza.</p>
<p>No gráfico <em>Q-Q Residuals</em> pode-se notar que os erros têm uma distribuição aproximadamente normal, já que os pontos estão próximos à linha pontilhada.</p>
<p>No gráfico do <em>Scale-Location</em> é possível observar que a variância dos resíduos é constante ao longo dos valores ajustados, o que indica que a suposição de homocedasticidade foi atendida.</p>
<p>No gráfico do <em>Residuals vs Leverage</em> os outliers identificados foram os pontos 248 e 358, com resíduos padronizados significativos, indicando que eles podem estar influenciando o ajuste do modelo. O ponto 357 também merece atenção, mas não é tão extremo quanto os outros.</p>
</section>
</section>
<section id="interpretações-do-modelo-selecionado" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Interpretações do modelo selecionado</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(report)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(modelo6)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a linear model (estimated using OLS) to predict Sales with CompPrice,
Income, Advertising, Price, ShelveLoc and Age (formula: Sales ~ CompPrice +
Income + Advertising + Price + ShelveLoc + Age). The model explains a
statistically significant and substantial proportion of variance (R2 = 0.87,
F(7, 392) = 381.44, p &lt; .001, adj. R2 = 0.87). The model's intercept,
corresponding to CompPrice = 0, Income = 0, Advertising = 0, Price = 0,
ShelveLoc = Bad and Age = 0, is at 5.48 (95% CI [4.48, 6.47], t(392) = 10.84, p
&lt; .001). Within this model:

  - The effect of CompPrice is statistically significant and positive (beta =
0.09, 95% CI [0.08, 0.10], t(392) = 22.45, p &lt; .001; Std. beta = 0.50, 95% CI
[0.46, 0.55])
  - The effect of Income is statistically significant and positive (beta = 0.02,
95% CI [0.01, 0.02], t(392) = 8.59, p &lt; .001; Std. beta = 0.16, 95% CI [0.12,
0.19])
  - The effect of Advertising is statistically significant and positive (beta =
0.12, 95% CI [0.10, 0.13], t(392) = 15.01, p &lt; .001; Std. beta = 0.27, 95% CI
[0.24, 0.31])
  - The effect of Price is statistically significant and negative (beta = -0.10,
95% CI [-0.10, -0.09], t(392) = -35.70, p &lt; .001; Std. beta = -0.80, 95% CI
[-0.84, -0.76])
  - The effect of ShelveLoc [Good] is statistically significant and positive
(beta = 4.84, 95% CI [4.54, 5.14], t(392) = 31.71, p &lt; .001; Std. beta = 1.71,
95% CI [1.61, 1.82])
  - The effect of ShelveLoc [Medium] is statistically significant and positive
(beta = 1.95, 95% CI [1.71, 2.20], t(392) = 15.57, p &lt; .001; Std. beta = 0.69,
95% CI [0.60, 0.78])
  - The effect of Age is statistically significant and negative (beta = -0.05,
95% CI [-0.05, -0.04], t(392) = -14.52, p &lt; .001; Std. beta = -0.26, 95% CI
[-0.30, -0.23])

Standardized parameters were obtained by fitting the model on a standardized
version of the dataset. 95% Confidence Intervals (CIs) and p-values were
computed using a Wald t-distribution approximation.</code></pre>
</div>
</div>
<p>Fizemos o ajuste de um modelo linear (estimado usando OLS) para prever <code>Sales</code> com <code>CompPrice</code>, <code>Income</code>, <code>Advertising</code>, <code>Price</code>, <code>ShelveLoc</code> e <code>Age</code> (fórmula: Sales ~ CompPrice + Income + Advertising + Price + ShelveLoc + Age). O modelo explica uma proporção estatisticamente significativa e substancial de variância (R² = 0,87, F(7, 392) = 381,44, p &lt; 0,001, R² ajustado = 0,87). O intercepto do modelo, correspondente a <code>CompPrice</code> = 0, <code>Income</code> = 0, <code>Advertising</code> = 0, <code>Price</code> = 0, <code>ShelveLoc</code> = Bad e <code>Age</code> = 0, é de 5,48 (IC 95% [4,48, 6,47], t(392) = 10,84, p &lt; 0,001). Dentro deste modelo:</p>
<section id="relato-em-português" class="level3" data-number="6.0.1">
<h3 data-number="6.0.1" class="anchored" data-anchor-id="relato-em-português"><span class="header-section-number">6.0.1</span> Relato em português:</h3>
<ul>
<li><p>O efeito de <code>CompPrice</code> é estatisticamente significativo e positivo (beta = 0,09, IC 95% [0,08, 0,10], t(392) = 22,45, p &lt; 0,001; Std. beta = 0,50, IC 95% [0,46, 0,55])</p></li>
<li><p>O efeito de <code>Renda</code> é estatisticamente significativo e positivo (beta = 0,02, IC 95% [0,01, 0,02], t(392) = 8,59, p &lt; 0,001; Std. beta = 0,16, IC 95% [0,12, 0,19])</p></li>
<li><p>O efeito de <code>Publicidade</code> é estatisticamente significativo e positivo (beta = 0,12, IC 95% [0,10, 0,13], t(392) = 15,01, p &lt; 0,001; Std. beta = 0,27, IC 95% [0,24, 0,31])</p></li>
<li><p>O efeito de <code>Preço</code> é estatisticamente significativo e negativo (beta = -0,10, IC 95% [-0,10, -0,09], t(392) = -35,70, p &lt; 0,001; Std. beta = -0,80, IC 95% [-0,84, -0,76])</p></li>
<li><p>O efeito de <code>Localização da Prateleira [Boa]</code> é estatisticamente significativo e positivo (beta = 4,84, IC 95% [4,54, 5,14], t(392) = 31,71, p &lt; 0,001; Std. beta = 1,71, IC 95% [1,61, 1,82])</p></li>
<li><p>O efeito de <code>Localização da Prateleira [Média]</code> é estatisticamente significativo e positivo (beta = 1,95, IC 95% [1,71, 2,20], t(392) = 15,57, p &lt; 0,001; Std. beta = 0,69, IC 95% [0,60, 0,78])</p></li>
<li><p>O efeito de Idade é estatisticamente significativo e negativo (beta = -0,05, IC 95% [-0,05, -0,04], t(392) = -14,52, p &lt; 0,001; Std. beta = -0,26, IC 95% [-0,30, -0,23])</p></li>
<li><p>Os parâmetros padronizados foram obtidos ajustando o modelo em uma versão padronizada do conjunto de dados. Os Intervalos de Confiança (ICs) de 95% e os valores de p foram calculados usando uma aproximação da distribuição t de Wald.</p></li>
</ul>
</section>
<section id="coeficientes-padronizados" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="coeficientes-padronizados"><span class="header-section-number">6.1</span> Coeficientes padronizados</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>lm.beta<span class="sc">::</span><span class="fu">lm.beta</span>(modelo6)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ CompPrice + Income + Advertising + Price + 
    ShelveLoc + Age, data = dados)

Standardized Coefficients::
    (Intercept)       CompPrice          Income     Advertising           Price 
             NA       0.5026489       0.1564238       0.2729350      -0.7991299 
  ShelveLocGood ShelveLocMedium             Age 
      0.7013309       0.3444615      -0.2646066 </code></pre>
</div>
</div>
</section>
</section>
<section id="previsões" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Previsões</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Sales          CompPrice       Income        Advertising    
 Min.   : 0.000   Min.   : 77   Min.   : 21.00   Min.   : 0.000  
 1st Qu.: 5.390   1st Qu.:115   1st Qu.: 42.75   1st Qu.: 0.000  
 Median : 7.490   Median :125   Median : 69.00   Median : 5.000  
 Mean   : 7.496   Mean   :125   Mean   : 68.66   Mean   : 6.635  
 3rd Qu.: 9.320   3rd Qu.:135   3rd Qu.: 91.00   3rd Qu.:12.000  
 Max.   :16.270   Max.   :175   Max.   :120.00   Max.   :29.000  
   Population        Price        ShelveLoc        Age          Education   
 Min.   : 10.0   Min.   : 24.0   Bad   : 96   Min.   :25.00   Min.   :10.0  
 1st Qu.:139.0   1st Qu.:100.0   Good  : 85   1st Qu.:39.75   1st Qu.:12.0  
 Median :272.0   Median :117.0   Medium:219   Median :54.50   Median :14.0  
 Mean   :264.8   Mean   :115.8                Mean   :53.32   Mean   :13.9  
 3rd Qu.:398.5   3rd Qu.:131.0                3rd Qu.:66.00   3rd Qu.:16.0  
 Max.   :509.0   Max.   :191.0                Max.   :80.00   Max.   :18.0  
 Urban       US     
 No :118   No :142  
 Yes:282   Yes:258  
                    
                    
                    
                    </code></pre>
</div>
</div>
<p>Agora, suponha que temos por objetivo prever os valores de vendas (<code>Sales</code>) considerando os seguintes valores para as variáveis explicativas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Novos valores das variáveis preditoras</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>novas.preditoras <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">CompPrice =</span> <span class="fu">c</span>(<span class="dv">120</span>, <span class="dv">150</span>), </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">Income =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">70</span>), </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">Advertising =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">20</span>), </span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>                                <span class="at">Price =</span> <span class="fu">c</span>(<span class="dv">99</span>, <span class="dv">95</span>), </span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>                                <span class="at">ShelveLoc =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">"Good"</span>, <span class="st">"Medium"</span>)), </span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">Age =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">30</span>))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Observação</strong>:</p>
<p>O data.frame <code>novas.preditoras</code> com os novos valores das variáveis preditoras deve ser construído com os mesmos nomes das variáveis preditoras utilizadas no objeto que contém o modelo ajustado.</p>
<section id="intervalo-de-confiança" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="intervalo-de-confiança"><span class="header-section-number">7.1</span> Intervalo de Confiança</h2>
<p>Um <strong>intervalo de confiança</strong> captura a incerteza em torno dos <strong>valores médios (valores esperados)</strong> preditos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modelo6, novas.preditoras,</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 13.00863 12.68342 13.33384
2 14.29683 13.88790 14.70576</code></pre>
</div>
</div>
<p>Para a primeira observação: A estimativa pontual para <code>Sales</code> é de aproximadamente 13.01. O intervalo de confiança é de [12.68, 13.33]. Isso significa que, com 95% de confiança, podemos afirmar que a média real das vendas para as condições especificadas (com <code>CompPrice</code> = 120, <code>Income</code> = 50, etc.) está entre 12.68 e 13.33.</p>
<p>Para a segunda observação: A estimativa pontual para <code>Sales</code> é de aproximadamente 14.30. O intervalo de confiança é de [13.89, 14.71]. Aqui também, temos 95% de confiança de que a média real das vendas para as condições especificadas (com <code>CompPrice</code> = 150, <code>Income</code> = 70, etc.) está entre 13.89 e 14.71.</p>
</section>
<section id="intervalo-de-prediçãoprevisão" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="intervalo-de-prediçãoprevisão"><span class="header-section-number">7.2</span> Intervalo de Predição/Previsão</h2>
<p>Um <strong>intervalo de predição</strong> captura a incerteza em torno de um <strong>único valor</strong> não observado na base de dados e não em torno do seu <strong>valor médio/esperado</strong> o qual é obtido pelas variáveis preditoras observadas na base de dados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modelo6, novas.preditoras,</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 13.00863 10.97817 15.03909
2 14.29683 12.25129 16.34237</code></pre>
</div>
</div>
<p>Para a primeira observação: A estimativa pontual para <code>Sales</code> é a mesma, 13.01. No entanto, o intervalo de predição é mais amplo, variando de [10.98, 15.04]. Isso indica que, para uma nova observação sob as mesmas condições, podemos esperar que as vendas estejam entre 10.98 e 15.04. Esse intervalo mais amplo reflete a incerteza relacionada a um único valor observado, que é maior do que a incerteza associada à média.</p>
<p>Para a segunda observação: A estimativa pontual permanece em 14.30, mas o intervalo de predição é [12.25, 16.34]. Isso sugere que, para uma nova observação, as vendas podem variar entre 12.25 e 16.34, refletindo também a variabilidade dos dados e a incerteza associada a um único valor.</p>
</section>
</section>
<section id="conclusão" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Conclusão</h1>
<p>A análise de regressão linear múltipla realizada sobre a base de dados <code>Carseats</code> forneceu insights valiosos sobre os fatores que influenciam as vendas de cadeirinhas de carro para crianças. O modelo ajustado, que incluiu variáveis como <code>CompPrice</code>, <code>Income</code>, <code>Advertising</code>, <code>Price</code>, <code>ShelveLoc</code> e <code>Age</code>, demonstrou um alto poder explicativo, com aproximadamente 87,34% da variação nas vendas sendo explicada pelas variáveis independentes.</p>
<p>As análises de correlação e a avaliação do Fator de Inflação da Variância (VIF) indicaram que não há problemas significativos de multicolinearidade entre as variáveis selecionadas. A remoção das variáveis <code>Population</code>, <code>Education</code>, <code>Urban</code> e <code>US</code> do modelo não resultou em uma perda significativa de poder preditivo, conforme indicado pelo ajuste de R².</p>
<p>Os resultados revelaram que:</p>
<ul>
<li><p><code>Preço</code> e <code>Publicidade</code> exercem efeitos positivos e significativos nas vendas, sugerindo que estratégias de marketing e posicionamento de preço podem influenciar substancialmente a demanda.</p></li>
<li><p>A <code>localização da prateleira</code> (especialmente em locais classificados como “Boa”) é um fator crucial que pode aumentar as vendas, enquanto uma <strong>maior idade da população</strong> está associada a uma redução nas vendas.</p></li>
<li><p>A <code>renda</code> média dos consumidores também demonstrou ter um impacto positivo, corroborando a importância do poder aquisitivo na decisão de compra.</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>